/* Rail Language grammar */


/* Expressions */

<Expression>
  ::= <LiteralExpression>
    | <OperatorExpression>
    | <GroupedExpression>

<NegationExpression>
  ::= "!" <Expression>
    | "-" <Expression>

<OperatorExpression>
  ::= <ArithmeticExpression>
    | <ComparisonExpression>
    | <LazyBooleanExpression>

<ArithmeticExpression>
  ::= <Expression> "+" <Expression>
    | <Expression> "-" <Expression>
    | <Expression> "*" <Expression>
    | <Expression> "/" <Expression>

<ComparisonExpression>
  ::= <Expression> "==" <Expression>
    | <Expression> "!=" <Expression>
    | <Expression> "<"  <Expression>
    | <Expression> "<=" <Expression>
    | <Expression> ">"  <Expression>
    | <Expression> ">=" <Expression>

<LazyBooleanExpression>
  ::= <Expression> "||" <Expression>
    | <Expression> "&&" <Expression>

<GroupedExpression> ::= "(" <Expression> ")"

<LiteralExpression>
  ::= <NumericLiteral>
    | <BoolLiteral>
    | <UnitLiteral>


/* Literals */

<Letter>
  ::= "A" | "B" | "C" | "D" | "E" | "F" | "G"
    | "H" | "I" | "J" | "K" | "L" | "M" | "N"
    | "O" | "P" | "Q" | "R" | "S" | "T" | "U"
    | "V" | "W" | "X" | "Y" | "Z" | "a" | "b"
    | "c" | "d" | "e" | "f" | "g" | "h" | "i"
    | "j" | "k" | "l" | "m" | "n" | "o" | "p"
    | "q" | "r" | "s" | "t" | "u" | "v" | "w"
    | "x" | "y" | "z"

<BinDigit> ::= "0" | "1"
<OctDigit> ::= "0" | "1" | "2" | "3" | "4" | "5" | "6" | "7"
<HexDigit> ::= "0" | "1" | "2" | "3" | "4" | "5" | "6" | "7" | "8" | "9" | "A" | "B" | "C" | "D" | "E" | "F"
<DecDigit> ::= "0" | "1" | "2" | "3" | "4" | "5" | "6" | "7" | "8" | "9"

<BinNumber> ::= "0b" <BinDigit>+
<OctNumber> ::= "0o" <OctDigit>+
<HexNumber> ::= "0x" <HexDigit>+
<DecNumber> ::= <DecDigit>+
<Number> ::= <BinNumber> | <OctNumber> | <HexNumber> | <DecNumber>

<Int64Number> ::= <Number> "i64"?

<Uint64Number> ::= <Number> "u64"

<Float64Number> ::= <DecNumber> "." <DecNumber> "f64"?

<IntegerLiteral>
  ::= <Int64Number>
    | <Uint64Number>

<FloatLiteral>
  ::= <Float64Number>

<NumericLiteral> ::= <IntegerLiteral> | <FloatLiteral>

<BoolLiteral> ::= "true" | "false"

<UnitLiteral> ::= "()"


/* Statements */

<Statement>
  ::= ";"
    | <ExpressionStatement>

<ExpressionStatement>
  ::= <Expression> ";"


/* Types */

<Type>
  ::= <ParethesizedType>
    | <NeverType>
    | <TupleType>

<ParethesizedType> ::= "(" <Type> ")"

<NeverType> ::= "!"

<TupleType>
  ::= "(" ")"
    | "(" (<Type> ",")+ <Type>? ")"
